import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author adrig
 */
public class VentanaBuscarPedido extends javax.swing.JFrame {

    /**
     * Creates new form VentanaBuscarPedido
     */
    public VentanaBuscarPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNombreVentana = new javax.swing.JLabel();
        jPanelDatosPedido = new javax.swing.JPanel();
        jLabelCodigoPedido = new javax.swing.JLabel();
        jLabelFechaPedido = new javax.swing.JLabel();
        jTextFieldFechaPedido = new javax.swing.JTextField();
        jLabelFechaEsperada = new javax.swing.JLabel();
        jTextFieldFechaEsperada = new javax.swing.JTextField();
        jLabelFechaEntrega = new javax.swing.JLabel();
        jTextFieldFechaEntrega = new javax.swing.JTextField();
        jLabelComentarios = new javax.swing.JLabel();
        jTextFieldComentarios = new javax.swing.JTextField();
        jLabelEstado = new javax.swing.JLabel();
        jTextFieldEstado = new javax.swing.JTextField();
        jLabelCodigoCliente = new javax.swing.JLabel();
        jTextFieldCodigoCliente = new javax.swing.JTextField();
        jTextFieldCodigoPedido = new javax.swing.JTextField();
        jButtonMostrarResultadosPedido = new javax.swing.JButton();
        jButtonLimpiarCampos = new javax.swing.JButton();
        jTextFieldPrecioTotal = new javax.swing.JTextField();
        jLabelPrecioTotal = new javax.swing.JLabel();
        jPanelDetallesPedido = new javax.swing.JPanel();
        jScrollPaneDetallesPedido = new javax.swing.JScrollPane();
        jTableDetallesPedido = new javax.swing.JTable();
        jToggleButtonVolverVentanaPrincipal = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabelNombreVentana.setFont(new java.awt.Font("Segoe UI", 1, 37)); // NOI18N
        jLabelNombreVentana.setText("DETALLES DEL PEDIDO:");

        jPanelDatosPedido.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PEDIDO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 20))); // NOI18N

        jLabelCodigoPedido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelCodigoPedido.setText("CODIGO PEDIDO:");

        jLabelFechaPedido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelFechaPedido.setText("FECHA PEDIDO:");

        jTextFieldFechaPedido.setEditable(false);
        jTextFieldFechaPedido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldFechaPedido.setEnabled(false);
        jTextFieldFechaPedido.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        jLabelFechaEsperada.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelFechaEsperada.setText("FECHA ESPERADA:");

        jTextFieldFechaEsperada.setEditable(false);
        jTextFieldFechaEsperada.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldFechaEsperada.setEnabled(false);

        jLabelFechaEntrega.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelFechaEntrega.setText("FECHA ENTREGA:");

        jTextFieldFechaEntrega.setEditable(false);
        jTextFieldFechaEntrega.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldFechaEntrega.setEnabled(false);

        jLabelComentarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelComentarios.setText("COMENTARIOS:");

        jTextFieldComentarios.setEditable(false);
        jTextFieldComentarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldComentarios.setEnabled(false);

        jLabelEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelEstado.setText("ESTADO:");

        jTextFieldEstado.setEditable(false);
        jTextFieldEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldEstado.setEnabled(false);

        jLabelCodigoCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelCodigoCliente.setText("CODIGO CLIENTE:");

        jTextFieldCodigoCliente.setEditable(false);
        jTextFieldCodigoCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldCodigoCliente.setEnabled(false);

        jTextFieldCodigoPedido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jButtonMostrarResultadosPedido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonMostrarResultadosPedido.setText("MOSTRAR RESULTADOS");
        jButtonMostrarResultadosPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarResultadosPedidoActionPerformed(evt);
            }
        });

        jButtonLimpiarCampos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonLimpiarCampos.setText("LIMPIAR CAMPOS");
        jButtonLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarCamposActionPerformed(evt);
            }
        });

        jTextFieldPrecioTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldPrecioTotal.setEnabled(false);

        jLabelPrecioTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelPrecioTotal.setText("PRECIO TOTAL DEL PEDIDO:");

        javax.swing.GroupLayout jPanelDatosPedidoLayout = new javax.swing.GroupLayout(jPanelDatosPedido);
        jPanelDatosPedido.setLayout(jPanelDatosPedidoLayout);
        jPanelDatosPedidoLayout.setHorizontalGroup(
            jPanelDatosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosPedidoLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanelDatosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosPedidoLayout.createSequentialGroup()
                        .addGroup(jPanelDatosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelDatosPedidoLayout.createSequentialGroup()
                                .addComponent(jLabelFechaPedido)
                                .addGap(15, 15, 15)
                                .addComponent(jTextFieldFechaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jLabelFechaEsperada)
                                .addGap(15, 15, 15)
                                .addComponent(jTextFieldFechaEsperada, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addComponent(jLabelFechaEntrega)
                                .addGap(15, 15, 15)
                                .addComponent(jTextFieldFechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelDatosPedidoLayout.createSequentialGroup()
                                .addComponent(jLabelComentarios)
                                .addGap(15, 15, 15)
                                .addComponent(jTextFieldComentarios))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelDatosPedidoLayout.createSequentialGroup()
                                .addComponent(jLabelCodigoPedido)
                                .addGap(15, 15, 15)
                                .addComponent(jTextFieldCodigoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(5, 5, 5))
                    .addGroup(jPanelDatosPedidoLayout.createSequentialGroup()
                        .addGroup(jPanelDatosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDatosPedidoLayout.createSequentialGroup()
                                .addComponent(jLabelEstado)
                                .addGap(15, 15, 15)
                                .addComponent(jTextFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jLabelCodigoCliente)
                                .addGap(15, 15, 15)
                                .addComponent(jTextFieldCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDatosPedidoLayout.createSequentialGroup()
                                .addComponent(jLabelPrecioTotal)
                                .addGap(15, 15, 15)
                                .addComponent(jTextFieldPrecioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanelDatosPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonMostrarResultadosPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonLimpiarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelDatosPedidoLayout.setVerticalGroup(
            jPanelDatosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosPedidoLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanelDatosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigoPedido)
                    .addComponent(jTextFieldCodigoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanelDatosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldFechaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFechaPedido)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelFechaEsperada)
                        .addComponent(jTextFieldFechaEsperada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelFechaEntrega)
                        .addComponent(jTextFieldFechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jPanelDatosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelComentarios)
                    .addComponent(jTextFieldComentarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanelDatosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEstado)
                    .addComponent(jTextFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCodigoCliente)
                    .addComponent(jTextFieldCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanelDatosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrecioTotal)
                    .addComponent(jTextFieldPrecioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanelDatosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonMostrarResultadosPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLimpiarCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );

        jPanelDetallesPedido.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DETALLES PEDIDO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 18))); // NOI18N

        jTableDetallesPedido.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jTableDetallesPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "CANTIDAD", "CODIGO PEDIDO", "CODIGO PRODUCTO", "NUMERO LINEA", "PRECIO UNIDAD"
            }
        ));
        jTableDetallesPedido.setEnabled(false);
        jScrollPaneDetallesPedido.setViewportView(jTableDetallesPedido);

        javax.swing.GroupLayout jPanelDetallesPedidoLayout = new javax.swing.GroupLayout(jPanelDetallesPedido);
        jPanelDetallesPedido.setLayout(jPanelDetallesPedidoLayout);
        jPanelDetallesPedidoLayout.setHorizontalGroup(
            jPanelDetallesPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetallesPedidoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPaneDetallesPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDetallesPedidoLayout.setVerticalGroup(
            jPanelDetallesPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetallesPedidoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPaneDetallesPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jToggleButtonVolverVentanaPrincipal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jToggleButtonVolverVentanaPrincipal.setText("VOLVER");
        jToggleButtonVolverVentanaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonVolverVentanaPrincipalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelNombreVentana)
                        .addComponent(jPanelDatosPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelDetallesPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jToggleButtonVolverVentanaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelNombreVentana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelDatosPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jPanelDetallesPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jToggleButtonVolverVentanaPrincipal)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMostrarResultadosPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarResultadosPedidoActionPerformed
        
        double sumaPrecioTotal = 0;
        
        Connection conexion = ConexionBD.getConexion();
        
        String codigoProducto = jTextFieldCodigoPedido.getText();
                
        PreparedStatement sentencia = null;
        
        try{  
            String sentenciaSQL = "SELECT * FROM pedido WHERE codigo_pedido LIKE ?";
            
            sentencia = conexion.prepareStatement(sentenciaSQL);
            
            sentencia.setString(1, codigoProducto);
            
            ResultSet rs = sentencia.executeQuery();   
            
            if(rs.next()){
                jTextFieldFechaPedido.setText(rs.getString("fecha_pedido"));
                jTextFieldFechaEsperada.setText(rs.getString("fecha_esperada"));
                jTextFieldFechaEntrega.setText(rs.getString("fecha_entrega"));
                jTextFieldComentarios.setText(rs.getString("comentarios"));
                jTextFieldEstado.setText(rs.getString("estado"));
                jTextFieldCodigoCliente.setText(rs.getString("codigo_cliente"));
            }
            else{
                JOptionPane.showMessageDialog(this,"El codigo de producto " + codigoProducto + " no existe en la base de datos.","ERROR CARGA DE DATOS",JOptionPane.WARNING_MESSAGE);
            }
            
            String sql = "SELECT * FROM detalle_pedido WHERE codigo_pedido LIKE ? ORDER BY numero_linea ASC";
            sentencia = conexion.prepareStatement(sql);
            sentencia.setString(1, codigoProducto);
            rs = sentencia.executeQuery();
            
            DefaultTableModel tabla = new DefaultTableModel();
            tabla.addColumn("NUMERO LINEA:");
            tabla.addColumn("CODIGO PEDIDO:");
            tabla.addColumn("CODIGO PRODUCTO:");
            tabla.addColumn("CANTIDAD:");
            tabla.addColumn("PRECIO UNIDAD:");
            
            while(rs.next()){
                String[] datosUsuarios = new String[5];
                datosUsuarios[0] = rs.getString("numero_linea");
                datosUsuarios[1] = rs.getString("codigo_pedido");
                datosUsuarios[2] = rs.getString("codigo_producto");
                datosUsuarios[3] = rs.getString("cantidad");
                datosUsuarios[4] = rs.getString("precio_unidad");
                tabla.addRow(datosUsuarios);
                
                double cantidad = Double.parseDouble(datosUsuarios[3]);
                double precioUnidad = Double.parseDouble(datosUsuarios[4]);
                double precioTotalFila = cantidad * precioUnidad;
                sumaPrecioTotal += precioTotalFila;
                
                jTableDetallesPedido.setModel(tabla);
            
                jTextFieldPrecioTotal.setText(String.valueOf(sumaPrecioTotal) + "€");
            }
        }
        catch (SQLException e){
            e.printStackTrace();
        } 
        catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonMostrarResultadosPedidoActionPerformed

    private void jButtonLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarCamposActionPerformed
        // TODO add your handling code here:
        int confirmarLimpiarCampos = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que desea limpiar todos los campos?", "LIMPIAR CAMPOS", JOptionPane.YES_NO_OPTION);
        
        if(confirmarLimpiarCampos == JOptionPane.YES_OPTION){
            jTextFieldCodigoPedido.setText("");
            jTextFieldFechaPedido.setText("");
            jTextFieldFechaEsperada.setText("");
            jTextFieldFechaEntrega.setText("");
            jTextFieldComentarios.setText("");
            jTextFieldEstado.setText("");
            jTextFieldCodigoCliente.setText("");
            jTextFieldPrecioTotal.setText("");

            DefaultTableModel tablaDetallesPedido = (DefaultTableModel) jTableDetallesPedido.getModel();
            tablaDetallesPedido.setRowCount(0);
        }
    }//GEN-LAST:event_jButtonLimpiarCamposActionPerformed

    private void jToggleButtonVolverVentanaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonVolverVentanaPrincipalActionPerformed
        // TODO add your handling code here:
        VentanaPrincipal newFrame = new VentanaPrincipal();
        
        newFrame.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jToggleButtonVolverVentanaPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaBuscarPedido().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLimpiarCampos;
    private javax.swing.JButton jButtonMostrarResultadosPedido;
    private javax.swing.JLabel jLabelCodigoCliente;
    private javax.swing.JLabel jLabelCodigoPedido;
    private javax.swing.JLabel jLabelComentarios;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelFechaEntrega;
    private javax.swing.JLabel jLabelFechaEsperada;
    private javax.swing.JLabel jLabelFechaPedido;
    private javax.swing.JLabel jLabelNombreVentana;
    private javax.swing.JLabel jLabelPrecioTotal;
    private javax.swing.JPanel jPanelDatosPedido;
    private javax.swing.JPanel jPanelDetallesPedido;
    private javax.swing.JScrollPane jScrollPaneDetallesPedido;
    private javax.swing.JTable jTableDetallesPedido;
    private javax.swing.JTextField jTextFieldCodigoCliente;
    private javax.swing.JTextField jTextFieldCodigoPedido;
    private javax.swing.JTextField jTextFieldComentarios;
    private javax.swing.JTextField jTextFieldEstado;
    private javax.swing.JTextField jTextFieldFechaEntrega;
    private javax.swing.JTextField jTextFieldFechaEsperada;
    private javax.swing.JTextField jTextFieldFechaPedido;
    private javax.swing.JTextField jTextFieldPrecioTotal;
    private javax.swing.JToggleButton jToggleButtonVolverVentanaPrincipal;
    // End of variables declaration//GEN-END:variables
}
