
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author adrig
 */
public class VentanaEditarPedido extends javax.swing.JFrame {

    private Connection conexion;
    private ResultSet rs;

    public void actualizarTablaPedido(){
        try{
            Statement st = conexion.createStatement( ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rs = st.executeQuery("SELECT codigo_pedido, estado, fecha_pedido, fecha_esperada, fecha_entrega, comentarios FROM pedido ORDER BY codigo_pedido");
             
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("CODIGO PEDIDO");
            modelo.addColumn("ESTADO");
            modelo.addColumn("FECHA PEDIDO");
            modelo.addColumn("FECHA ESPERADA");
            modelo.addColumn("FECHA ENTREGA");
            modelo.addColumn("COMENTARIO");
             
            String[] result = new String[6];
            while(rs.next()){
                result[0] = rs.getString(1);
                result[1] = rs.getString(2);
                result[2] = rs.getString(3);
                result[3] = rs.getString(4);
                result[4] = rs.getString(5);
                result[5] = rs.getString(6);
                modelo.addRow(result);
            }
            jTablePedidos.setModel(modelo);
            rs.beforeFirst();
        } 
        catch (SQLException ex){
            System.out.println(ex);
        }
    }
    
    private void actualizarTablaDetallesPedido(String codigoPedido){
    try{
        String sql = "SELECT * FROM detalle_pedido WHERE codigo_pedido LIKE ? ORDER BY numero_linea ASC";
        PreparedStatement sentencia = conexion.prepareStatement(sql);
        sentencia.setString(1, codigoPedido);
        rs = sentencia.executeQuery();

        DefaultTableModel tabla = new DefaultTableModel();
        tabla.addColumn("NUMERO LINEA:");
        tabla.addColumn("CODIGO PEDIDO:");
        tabla.addColumn("CODIGO PRODUCTO:");
        tabla.addColumn("CANTIDAD:");
        tabla.addColumn("PRECIO UNIDAD:");

        while(rs.next()){
            String[] datosUsuarios = new String[5];
            datosUsuarios[0] = rs.getString("numero_linea");
            datosUsuarios[1] = rs.getString("codigo_pedido");
            datosUsuarios[2] = rs.getString("codigo_producto");
            datosUsuarios[3] = rs.getString("cantidad");
            datosUsuarios[4] = rs.getString("precio_unidad");
            tabla.addRow(datosUsuarios);
        }
        
        jTableDetallesPedido.setModel(tabla);
    } 
    catch (SQLException e){
        e.printStackTrace();
    }catch (Exception e) {
        e.printStackTrace();
    }
}
    
    public VentanaEditarPedido(){
        initComponents();
        
        conexion = ConexionBD.getConexion();
        actualizarTablaPedido();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNombreVentana = new javax.swing.JLabel();
        jPanelPedidos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePedidos = new javax.swing.JTable();
        jToggleButtonMostrarProductos = new javax.swing.JToggleButton();
        jPanelProductosPedido = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDetallesPedido = new javax.swing.JTable();
        jToggleButtonEliminarProducto = new javax.swing.JToggleButton();
        jPanelEditarCantidadProducto = new javax.swing.JPanel();
        jLabelCodigoProducto = new javax.swing.JLabel();
        jLabelCantidad = new javax.swing.JLabel();
        jTextFieldCodigoProducto = new javax.swing.JTextField();
        jTextFieldCantidadProducto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jToggleButtonVolver = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelNombreVentana.setFont(new java.awt.Font("Segoe UI", 1, 37)); // NOI18N
        jLabelNombreVentana.setText("EDITAR PEDIDO:");

        jPanelPedidos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PEDIDOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 20))); // NOI18N

        jTablePedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CODIGO PEDIDO", "ESTADO", "FECHA PEDIDO", "FECHA ESPERADA", "FECHA ENTREGA", "COMENTARIO"
            }
        ));
        jScrollPane1.setViewportView(jTablePedidos);

        jToggleButtonMostrarProductos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jToggleButtonMostrarProductos.setText("MOSTRAR PRODUCTOS");
        jToggleButtonMostrarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonMostrarProductosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPedidosLayout = new javax.swing.GroupLayout(jPanelPedidos);
        jPanelPedidos.setLayout(jPanelPedidosLayout);
        jPanelPedidosLayout.setHorizontalGroup(
            jPanelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPedidosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToggleButtonMostrarProductos)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanelPedidosLayout.setVerticalGroup(
            jPanelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPedidosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jToggleButtonMostrarProductos)
                .addGap(10, 10, 10))
        );

        jPanelProductosPedido.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PRODUCTOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 20))); // NOI18N

        jTableDetallesPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NUMERO LINEA:", "CODIGO PEDIDO:", "CODIGO PRODUCTO:", "CANTIDAD:", "PRECIO UNIDAD:"
            }
        ));
        jTableDetallesPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDetallesPedidoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableDetallesPedido);

        jToggleButtonEliminarProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jToggleButtonEliminarProducto.setText("ELIMINAR PRODUCTO");
        jToggleButtonEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonEliminarProductoActionPerformed(evt);
            }
        });

        jPanelEditarCantidadProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "EDITAR CANTIDAD PRODUCTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 15))); // NOI18N

        jLabelCodigoProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelCodigoProducto.setText("CODIGO PRODUCTO:");

        jLabelCantidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelCantidad.setText("NUEVA CANTIDAD PRODUCTO:");

        jTextFieldCodigoProducto.setEditable(false);
        jTextFieldCodigoProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldCodigoProducto.setEnabled(false);

        jTextFieldCantidadProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("ACTUALIZAR CANTIDAD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEditarCantidadProductoLayout = new javax.swing.GroupLayout(jPanelEditarCantidadProducto);
        jPanelEditarCantidadProducto.setLayout(jPanelEditarCantidadProductoLayout);
        jPanelEditarCantidadProductoLayout.setHorizontalGroup(
            jPanelEditarCantidadProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditarCantidadProductoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanelEditarCantidadProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(jPanelEditarCantidadProductoLayout.createSequentialGroup()
                        .addGroup(jPanelEditarCantidadProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCodigoProducto)
                            .addComponent(jLabelCantidad))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelEditarCantidadProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldCodigoProducto)
                            .addComponent(jTextFieldCantidadProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanelEditarCantidadProductoLayout.setVerticalGroup(
            jPanelEditarCantidadProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditarCantidadProductoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelEditarCantidadProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigoProducto)
                    .addComponent(jTextFieldCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEditarCantidadProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCantidad)
                    .addComponent(jTextFieldCantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelProductosPedidoLayout = new javax.swing.GroupLayout(jPanelProductosPedido);
        jPanelProductosPedido.setLayout(jPanelProductosPedidoLayout);
        jPanelProductosPedidoLayout.setHorizontalGroup(
            jPanelProductosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductosPedidoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelProductosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanelProductosPedidoLayout.createSequentialGroup()
                        .addComponent(jPanelEditarCantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButtonEliminarProducto))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanelProductosPedidoLayout.setVerticalGroup(
            jPanelProductosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductosPedidoLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelProductosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelProductosPedidoLayout.createSequentialGroup()
                        .addComponent(jToggleButtonEliminarProducto)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanelEditarCantidadProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jToggleButtonVolver.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jToggleButtonVolver.setText("VOLVER");
        jToggleButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelNombreVentana)
                    .addComponent(jPanelPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelProductosPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButtonVolver)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelNombreVentana)
                .addGap(5, 5, 5)
                .addComponent(jPanelPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanelProductosPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(jToggleButtonVolver)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonMostrarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonMostrarProductosActionPerformed
        // TODO add your handling code here:
        PreparedStatement sentencia = null;
           
        int selectedRow = jTablePedidos.getSelectedRow();
        if(selectedRow != -1){
            String codigoPedido = (String)jTablePedidos.getValueAt(selectedRow, 0);
            String estadoPedido = (String)jTablePedidos.getValueAt(selectedRow, 1);

            if (estadoPedido.equals("Rechazado") || estadoPedido.equals("Recibido") || estadoPedido.equals("Entregado")) {
                JOptionPane.showMessageDialog(this, "El pedido no puede ser modificado porque ya ha sido entregado al cliente o rechazado por este mismo.", "ERROR CARGA DE PRODUCTOS DEL PEDIDO", JOptionPane.WARNING_MESSAGE);
            } 
            else {
                actualizarTablaDetallesPedido(codigoPedido);
            }
        }
    }//GEN-LAST:event_jToggleButtonMostrarProductosActionPerformed

    private void jToggleButtonEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonEliminarProductoActionPerformed
        // TODO add your handling code here:

        int selectedRow = jTableDetallesPedido.getSelectedRow();
        if(selectedRow != -1){
            String codigoPedido = (String)jTableDetallesPedido.getValueAt(selectedRow, 1);
            String codigoProducto = (String)jTableDetallesPedido.getValueAt(selectedRow, 2);
            String cantidadProducto = (String)jTableDetallesPedido.getValueAt(selectedRow, 3);
            
            try{
                String contarFilas = "SELECT COUNT(*) FROM detalle_pedido WHERE codigo_pedido = ?";
                PreparedStatement sentenciaContarFilas = conexion.prepareStatement(contarFilas);
                sentenciaContarFilas.setString(1, codigoPedido);
                ResultSet contarFilasResult = sentenciaContarFilas.executeQuery();
                contarFilasResult.next();
                int numeroFilas = contarFilasResult.getInt(1);
                sentenciaContarFilas.close();

                if(numeroFilas == 1){
                    JOptionPane.showMessageDialog(this, "El pedido no puede quedar sin productos.", "ERROR ELIMINAR PRODUCTO", JOptionPane.WARNING_MESSAGE);
                    return;  // No se permite eliminar el producto
                }
                else{
                    int confirmResult = JOptionPane.showConfirmDialog(this, "¿Desea eliminar el producto que ha seleccionado?", "COMFIRMACION ELIMINAR PRODUCTO", JOptionPane.YES_NO_OPTION);
                    if(confirmResult == JOptionPane.YES_OPTION){
                        try{
                            String sentenciaActualizarStock = "UPDATE producto SET cantidad_en_stock = cantidad_en_stock + ? WHERE codigo_producto = ?";
                            PreparedStatement sentenciaSumarStock = conexion.prepareStatement(sentenciaActualizarStock);
                            sentenciaSumarStock.setString(1, cantidadProducto);
                            sentenciaSumarStock.setString(2, codigoProducto);
                            sentenciaSumarStock.executeUpdate();
                            sentenciaSumarStock.close();

                            String sentenciaEliminarProductoPedido = "DELETE FROM detalle_pedido WHERE codigo_pedido = ? AND codigo_producto = ?";
                            PreparedStatement sentenciaEliminarProducto = conexion.prepareStatement(sentenciaEliminarProductoPedido);
                            sentenciaEliminarProducto.setString(1, codigoPedido);
                            sentenciaEliminarProducto.setString(2, codigoProducto);
                            sentenciaEliminarProducto.executeUpdate();
                            sentenciaEliminarProducto.close();  
                        } 
                        catch (SQLException e) {
                            e.printStackTrace();
                        } catch (Exception e) {
                            e.printStackTrace();
                        }

                        actualizarTablaDetallesPedido(codigoPedido);
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Se ha cancelado la eliminación del pedido.");
                    }
                }
            }
            catch (SQLException e) {
                e.printStackTrace();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jToggleButtonEliminarProductoActionPerformed

    private void jToggleButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonVolverActionPerformed
        // TODO add your handling code here:
        VentanaPrincipal newFrame = new VentanaPrincipal();
        
        newFrame.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jToggleButtonVolverActionPerformed

    private void jTableDetallesPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDetallesPedidoMouseClicked
        // TODO add your handling code here:
        int selectedRow = jTableDetallesPedido.getSelectedRow();

        Object codProducto = jTableDetallesPedido.getValueAt(selectedRow, 2);

        jTextFieldCodigoProducto.setText(codProducto.toString());
    }//GEN-LAST:event_jTableDetallesPedidoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String cantidadProducto = "";
        
        int selectedRow = jTableDetallesPedido.getSelectedRow();
        if(selectedRow != -1){
            String codigoPedido = (String)jTableDetallesPedido.getValueAt(selectedRow, 1);
            cantidadProducto = (String)jTableDetallesPedido.getValueAt(selectedRow, 3);
        }
        
        String codigoProducto = jTextFieldCodigoProducto.getText();
        String nuevaCantidadProducto = jTextFieldCantidadProducto.getText();
        
        try{
            String sentenciaSumarCantidadStock = "UPDATE producto SET cantidad_en_stock = cantidad_en_stock + ? WHERE codigo_producto = ?";
            PreparedStatement sentenciaActualizarStock = conexion.prepareStatement(sentenciaSumarCantidadStock);
            sentenciaActualizarStock.setString(1, cantidadProducto);
            sentenciaActualizarStock.setString(2, codigoProducto);
            sentenciaActualizarStock.executeUpdate();
            sentenciaActualizarStock.close();
            
            
            String sentenciaConsultarCantidadStock = "SELECT cantidad_en_stock FROM producto WHERE codigo_producto = ?";
            PreparedStatement sentenciaStock = conexion.prepareStatement(sentenciaConsultarCantidadStock);
            sentenciaStock.setString(1, codigoProducto);

            ResultSet rs = sentenciaStock.executeQuery();

            String cantidadStockProducto = "";
            while(rs.next()) {
                cantidadStockProducto = rs.getString("cantidad_en_stock");
            }

            System.out.println(cantidadStockProducto);
            sentenciaStock.close();
            
            
            if(Integer.parseInt(nuevaCantidadProducto) > Integer.parseInt(cantidadStockProducto)){
                JOptionPane.showMessageDialog(this, "La cantidad introducida es superior al stock disponible del producto.", "ERROR CANTIDAD PRODUCTO INVALIDA", JOptionPane.WARNING_MESSAGE);
            }
            else{
                String sentenciaQuitarStock = "UPDATE producto SET cantidad_en_stock = cantidad_en_stock - ? WHERE codigo_producto = ?";
                PreparedStatement sentenciaActualizarCantidadStock = conexion.prepareStatement(sentenciaQuitarStock);
                sentenciaActualizarCantidadStock.setString(1, nuevaCantidadProducto);
                sentenciaActualizarCantidadStock.setString(2, codigoProducto);
                sentenciaActualizarCantidadStock.executeUpdate();
                sentenciaActualizarCantidadStock.close();
            }
            System.out.println(cantidadStockProducto);
            
        }
        catch(SQLException e){
            e.printStackTrace();
        }catch (Exception e){
            e.printStackTrace();
        }        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEditarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEditarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEditarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEditarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEditarPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelCodigoProducto;
    private javax.swing.JLabel jLabelNombreVentana;
    private javax.swing.JPanel jPanelEditarCantidadProducto;
    private javax.swing.JPanel jPanelPedidos;
    private javax.swing.JPanel jPanelProductosPedido;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableDetallesPedido;
    private javax.swing.JTable jTablePedidos;
    private javax.swing.JTextField jTextFieldCantidadProducto;
    private javax.swing.JTextField jTextFieldCodigoProducto;
    private javax.swing.JToggleButton jToggleButtonEliminarProducto;
    private javax.swing.JToggleButton jToggleButtonMostrarProductos;
    private javax.swing.JToggleButton jToggleButtonVolver;
    // End of variables declaration//GEN-END:variables
}
